spring:
  application:
    name: user-service

  flyway:
    url: ${DB_JDBC_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    locations: classpath:db/migration

  main:
    web-application-type: reactive

  jackson:
    serialization:
      indent-output: true

server:
  port: 8084

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.web.reactive.function.client.WebClient: DEBUG
    org.springframework.data.r2dbc.core: DEBUG
    org.springframework.security: DEBUG

postgresql:
  host: ${DB_HOST}
  port: 5432
  database: userdb
  schema: public
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  ssl: allow

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600 # in seconds
    header: Authorization
    prefix: Bearer
