name: Deploy User Service to AWS ECS


on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      VPC_ID: ${{ secrets.VPC_ID }}
      SUBNET_IDS: ${{ secrets.SUBNET_IDS }}
      SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
      ALB_ARN: ${{ secrets.ALB_ARN }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_JDBC_URL: ${{ secrets.DB_JDBC_URL }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init, Import & Apply ECR
        working-directory: ./terraform/ecr
        run: |
          terraform init
          terraform import -allow-missing-config aws_ecr_repository.user_service user-service || true
          terraform apply -auto-approve

      - name: Get ECR Repository URL
        id: get_ecr_url
        working-directory: ./terraform/ecr
        run: |
          echo "ECR_REPOSITORY_URL=$(terraform output -raw ecr_repository_url)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY_URL }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY_URL }}:latest .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REPOSITORY_URL }}:latest

      - name: Terraform Init ECS
        working-directory: ./terraform/ecs
        run: terraform init

      - name: Terraform Apply ECS
        working-directory: ./terraform/ecs
        env:
          ECR_IMAGE_URL: ${{ env.ECR_REPOSITORY_URL }}:latest
        run: |
          terraform apply -auto-approve \
            -var="vpc_id=${{ env.VPC_ID }}" \
            -var="subnet_ids=${{ env.SUBNET_IDS }}" \
            -var="security_group_id=${{ env.SECURITY_GROUP_ID }}" \
            -var="alb_arn=${{ env.ALB_ARN }}" \
            -var="ecr_image_url=${{ env.ECR_IMAGE_URL }}"
